quarkus.http.port=8082

#----------------- datasource -----------------#
quarkus.datasource.db-kind=oracle
quarkus.datasource.username=dbUsername
quarkus.datasource.password=dbPassword
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@//127.0.0.1:1521/CORE
quarkus.hibernate-orm.schema-management.strategy=update


quarkus.http.non-application-root-path=q

#----------------- rest-client -----------------#
quarkus.rest-client.cb-api.url=http://localhost:8081
quarkus.rest-client.logging.scope=request-response
quarkus.rest-client.logging.body-limit=1024
